### ISSUE TITLE
proglem with beta version?

### ISSUE THREAD

**Issue by Dand89** [brupje/arduino-board-index#1]
Hi Guys, 
Am I the only one having problems with the new beta version of the package RRW?

"
Skipping contributed index file C:\Users\xxx\AppData\Local\Arduino15\package_rrw_beta_index.json, parsing error occured:
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (FileInputStream); line: 8, column: 2]
"

BR,
Dan

**Comment by brupje** [comment]
Loads fine in Arduino for me, did you this link: https://raw.githubusercontent.com/brupje/arduino-board-index/master/package_rrw_beta_index.json ?

**Comment by Dand89** [comment]
With the link you sent here it works. 
I only tried before with this link. 
https://github.com/brupje/arduino-board-index/blob/master/package_rrw_beta_index.json

**Comment by brupje** [comment]
Yeah, that is the HTML page version. Arduino doesn't accept that.
